---
# tasks file for roles/certs
- name: Générer la clé privée SSH
  ansible.builtin.command:
    cmd: "ssh-keygen -t {{ ssh_key_type }} -b {{ ssh_key_bits }} -f {{ ssh_key_path }} -N ''"
    creates: "{{ ssh_key_path }}"

- name: Générer la clé publique SSH à partir de la clé privée
  ansible.builtin.command:
    cmd: "ssh-keygen -y -f {{ ssh_key_path }} > {{ ssh_key_path }}.pub"
    creates: "{{ ssh_key_path }}.pub"

- name: Copier la clé publique
  ansible.builtin.copy:
    src: "{{ ssh_key_path }}.pub"
    dest: "{{ ssh_user_home }}/.ssh/authorized_keys"
    mode: '0644'
    remote_src: yes
  become: yes
  become_user: "{{ ssh_user }}"

- name: Configurer le fichier sshd_config
  ansible.builtin.lineinfile:
    path: "/etc/ssh/{{file_config}}"
    regexp: '^#AuthorizedKeysFile'
    line: 'AuthorizedKeysFile .ssh/authorized_keys'
    state: present
  become: yes
